### ISSUE TITLE
搞个CLI工具，支持UNIX系

### ISSUE THREAD

**Issue by wwhai** [zengming00/mrpbuilder#1]
搞个命令行工具，能直接在UNIX系系统下面创建、编译项目

**Comment by zengming00** [comment]
就知道说，编译用的gcc，打包工具用go语言写的，哪个不支持*nix?

**Comment by wwhai** [comment]
> 就知道说，编译用的gcc，打包工具用go语言写的，哪个不支持*nix?

I means `cli tools` such as:
```
mrpcli new app <name>
mrpcli new game <name>
mrpcli build
mrpcli debug
mrpcli clean
mrpcli release
```

**Comment by wwhai** [comment]
> > 就知道说，编译用的gcc，打包工具用go语言写的，哪个不支持*nix?
> 
> I means `cli tools` such as:
> 
> ```
> mrpcli new app <name>
> mrpcli new game <name>
> mrpcli build
> mrpcli debug
> mrpcli clean
> mrpcli release
> ```

I guessed you won't focus on this issue, So I close it.
